version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      
    steps:
      - checkout
      - run: curl -sSL https://get.haskellstack.org/ | sh
      - run: stack setup
      - run: stack build
      - run: cd _site/ && git add --all
      - run: cd _site/ && git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
      - run: cd _site/ && git push origin master