version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
      
    steps:
      - run: 
          name: "install tools"
          command: |
            sudo apt update && sudo apt install ruby && gem install html-proofer
      - checkout
      - run:
          name: "Setup stack"
          command: |
            stack setup
      - run: 
          name: "Build site compiler"
          command: |
            stack build
      - run: 
          name: "Build site"
          command: |
            stack exec site build
      - run: 
          name: "Check for issues"
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external
      - deploy:
          name: deploy to the main branch
          command: |
            if [ "${CIRCLE_BRANCH}" = "hakyll" ]; then
              git subtree split --branch main --prefix _site/
            else
              echo "Not deployment branch, dry run only"
            fi