version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
      
    steps:
      - checkout
      - run: stack setup
      - run: stacl build
      - run: cd _site/ && git add --all
      - run: cd _site/ && git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
      - run: cd _site/ && git push origin master